---
- name: Deploy container to AWS
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Pull Docker image locally
      command: docker pull servian/techchallengeapp:latest

    - name: Launch EC2 instance
      ec2:
        instance_type: t2.micro
        image: ami-0d55b159cbfafe1f0
        key_name: testkey
        wait: true
        region: us-west-2
        count: 1
        group: testsecuritygroup
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Install Docker on EC2 instance
      become: yes
      become_method: sudo
      shell: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Save Docker image as tar archive
      command: docker save servian/techchallengeapp:latest > techchallengeapp.tar

    - name: Copy Docker image to EC2 instance
      copy:
        src: techchallengeapp.tar
        dest: /tmp/

    - name: Load Docker image on EC2 instance
      become: yes
      become_method: sudo
      shell: |
        cd /tmp/
        docker load < techchallengeapp.tar

    - name: Run Docker container
      command: docker run -d -p 80:80 techchallengeapp:latest


